STATUS_ATANDI = "Atandı"
STATUS_GIRIS_MAILI_BEKLIYOR = "Giriş Maili Bekliyor"
STATUS_TT_ONAY_BEKLIYOR = "TT Onay Bekliyor"
STATUS_HAK_EDIS_BEKLEMEDE = "Hak Ediş Beklemede"
STATUS_HAK_EDIS_ALINDI = "Hak Ediş Alındı"
STATUS_TAMAMLANDI = "Tamamlandı"
STATUS_RET = "Ret"

STATUSES = [
    STATUS_ATANDI, 
    STATUS_GIRIS_MAILI_BEKLIYOR, 
    STATUS_TT_ONAY_BEKLIYOR, 
    STATUS_HAK_EDIS_BEKLEMEDE, 
    STATUS_HAK_EDIS_ALINDI, 
    STATUS_TAMAMLANDI, 
    STATUS_RET
]

ROLES = ["Admin", "Yönetici", "Müdür", "Saha Personeli"]
