STATUS_ATANDI = "Atandı"
STATUS_GIRIS_MAILI_BEKLIYOR = "Giriş Maili Bekliyor"
STATUS_TAMAMLANDI = "Tamamlandı"
STATUS_TT_ONAY_BEKLIYOR = "TT Onay Bekliyor"
STATUS_RET = "Ret"
STATUS_HAK_EDIS_BEKLEMEDE = "Hak Ediş Beklemede"
STATUS_HAK_EDIS_ALINDI = "Hak Ediş Alındı"

STATUSES = [
    STATUS_ATANDI,
    STATUS_GIRIS_MAILI_BEKLIYOR,
    STATUS_TAMAMLANDI,
    STATUS_TT_ONAY_BEKLIYOR,
    STATUS_RET,
    STATUS_HAK_EDIS_BEKLEMEDE,
    STATUS_HAK_EDIS_ALINDI
]

HAK_EDIS_STATUSES = [
    STATUS_HAK_EDIS_BEKLEMEDE,
    STATUS_HAK_EDIS_ALINDI
]
